CREATE NONCLUSTERED INDEX ACOUNT_PARENT_IDX ON dbo.ACCOUNT
  (PARENT_ID)
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO
CREATE NONCLUSTERED INDEX ACCOUNT_PARENT_DIRECT_IDX ON dbo.ACCOUNT
  (PARENT_DIRECT_ID)
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO
ALTER TABLE dbo.ACCOUNT
ADD CONSTRAINT ACCOUNT_NUMBER_UK 
UNIQUE NONCLUSTERED (ACCOUNT_NUMBER)
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO
CREATE NONCLUSTERED INDEX ACCOUNT_MEMBER_USER_IDX ON dbo.ACCOUNT
  (MEMBER_ID, USER_ID)
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO
ALTER TABLE dbo.USERS
ADD CONSTRAINT USERS_NAME_UK 
UNIQUE NONCLUSTERED (USER_NAME)
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO
CREATE NONCLUSTERED INDEX ACCOUNT_BONUS_MONTH_IDX ON dbo.ACCOUNT_BONUS
  (MONTH)
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO
CREATE NONCLUSTERED INDEX ACCOUNT_PRE_CALC_LEVEL_IDX ON dbo.ACCOUNT_PRE_CALC
  (CALC_ACCOUNT_ID, ACCOUNT_LEVEL, IS_CALCULATED)
WITH (
  PAD_INDEX = OFF,
  DROP_EXISTING = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  SORT_IN_TEMPDB = OFF,
  ONLINE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
GO