use dcap
go

create view dbo.BANG_KE_FULL_VW as
with bonus as (
SELECT     SUM(BONUS_AMOUNT) AS TONG, 
SUM(
CASE BONUS_TYPE
  WHEN 'TT' THEN BONUS_AMOUNT
  WHEN 'CC' THEN BONUS_AMOUNT
  WHEN 'HT' THEN BONUS_AMOUNT
  ELSE 0
END) AS HE_THONG,
SUM(
CASE BONUS_TYPE
  WHEN 'QL1' THEN BONUS_AMOUNT
  WHEN 'CC1' THEN BONUS_AMOUNT
  WHEN 'QL2' THEN BONUS_AMOUNT
  WHEN 'CC2' THEN BONUS_AMOUNT
  WHEN 'QL3' THEN BONUS_AMOUNT
  WHEN 'CC3' THEN BONUS_AMOUNT
  WHEN 'QL4' THEN BONUS_AMOUNT
  WHEN 'CC4' THEN BONUS_AMOUNT
  WHEN 'QL5' THEN BONUS_AMOUNT
  WHEN 'CC5' THEN BONUS_AMOUNT
  WHEN 'QL6' THEN BONUS_AMOUNT
  WHEN 'CC6' THEN BONUS_AMOUNT
  ELSE 0
END) AS QUAN_LY,
SUM(
CASE BONUS_TYPE
  WHEN 'ADD' THEN BONUS_AMOUNT
  ELSE 0
END) AS THUONG_THEM,
MONTH , ACCOUNT_ID
FROM         dbo.ACCOUNT_BONUS
GROUP BY MONTH, ACCOUNT_ID)
select ROW_NUMBER() OVER (ORDER BY ab.TONG desc) AS STT, child.HO_TEN AS TEN_NHAN_VIEN, usr.USER_NAME, child.GIOI_TINH, child.SO_CMND, 
child.NGAY_CAP, child.DIA_CHI, child.SO_TAI_KHOAN, child.CHI_NHANH_NH, child.SO_DIEN_THOAI, child.CREATED_DATE AS NGAY_DANG_KY,
ab.HE_THONG, ab.QUAN_LY, ab.THUONG_THEM, ab.TONG
FROM bonus AS ab INNER JOIN
     dbo.ACCOUNT AS ca ON ab.ACCOUNT_ID = ca.ACCOUNT_ID INNER JOIN
     dbo.MEMBER_INFO AS child ON ca.MEMBER_ID = child.MEMBER_ID INNER JOIN
     dbo.USERS AS usr ON ca.USER_ID = usr.USER_ID
go
