CREATE TABLE dbo.users (
  USER_ID numeric(10, 0) IDENTITY(1, 1) NOT NULL,
  USER_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  PASSWORD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  PRIMARY KEY CLUSTERED (USER_ID)
    WITH (
      PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF,
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
ON [PRIMARY]
GO

CREATE TABLE dbo.USER_ROLE (
  ROLE_ID numeric(10, 0) NOT NULL,
  USER_ID numeric(10, 0) NOT NULL,
  IS_ACTIVE numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (ROLE_ID, USER_ID)
)
GO

CREATE TABLE dbo.ROLES (
  ROLE_ID numeric(10, 0) IDENTITY(1, 1) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  DESCRIPTION nvarchar(200) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (ROLE_ID),
  UNIQUE (ROLE_CODE)
)
GO

CREATE TABLE dbo.ROLE_OBJECT (
  OBJECT_ID numeric(10, 0) NOT NULL,
  ROLE_ID numeric(10, 0) NOT NULL,
  IS_ACTIVE numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (OBJECT_ID, ROLE_ID)
)
GO

CREATE TABLE dbo.OBJECTS (
  OBJECT_ID numeric(10, 0) IDENTITY(1, 1) NOT NULL,
  PARENT_ID numeric(10, 0) NULL,
  OBJECT_CODE varchar(50) NULL,
  DESCRIPTION nvarchar(200) NULL,
  OBJECT_URL varchar(500) NULL,
  [ORDER] numeric(5, 0) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NULL,
  PRIMARY KEY CLUSTERED (OBJECT_ID),
  UNIQUE (OBJECT_CODE)
)
GO

CREATE TABLE dbo.MEMBER_INFO (
  MEMBER_ID numeric(7, 0) NOT NULL,
  HO_TEN nvarchar(100) NOT NULL,
  NGAY_SINH date NULL,
  SO_CMND varchar(15) NOT NULL,
  SO_DIEN_THOAI varchar(15) NULL,
  SO_TAI_KHOAN varchar(15) NULL,
  CHI_NHANH_NH nvarchar(100) NULL,
  MEMBER_CODE varchar(30) NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID),
  UNIQUE (SO_CMND),
  UNIQUE (MEMBER_CODE)
)
GO

CREATE TABLE dbo.MEMBER_TREE_L1 (
  MEMBER_ID numeric(7, 0) NOT NULL,
  MEMBER_INDEX numeric(1, 0) NOT NULL,
  PARENT_ID numeric(7, 0) NULL,
  CHILDREN_ID varchar(30) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MEMBER_TREE_L2 (
  MEMBER_ID numeric(7, 0) NOT NULL,
  MEMBER_INDEX numeric(1, 0) NOT NULL,
  PARENT_ID numeric(7, 0) NULL,
  CHILDREN_ID varchar(30) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MEMBER_TREE_L3 (
  MEMBER_ID numeric(7, 0) NOT NULL,
  MEMBER_INDEX numeric(1, 0) NOT NULL,
  PARENT_ID numeric(7, 0) NULL,
  CHILDREN_ID varchar(30) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MANAGER_TREE_L1 (
  MEMBER_ID numeric(7, 0) NOT NULL,
  MEMBER_INDEX numeric(1, 0) NOT NULL,
  PARENT_ID numeric(7, 0) NULL,
  CHILDREN_ID varchar(30) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MANAGER_TREE_L2 (
  MEMBER_ID numeric(7, 0) NOT NULL,
  MEMBER_INDEX numeric(1, 0) NOT NULL,
  PARENT_ID numeric(7, 0) NULL,
  CHILDREN_ID varchar(30) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MANAGER_TREE_L3 (
  MEMBER_ID numeric(7, 0) NOT NULL,
  MEMBER_INDEX numeric(1, 0) NOT NULL,
  PARENT_ID numeric(7, 0) NULL,
  CHILDREN_ID varchar(30) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MANAGER_TREE_L4 (
  MEMBER_ID numeric(7, 0) NOT NULL,
  MEMBER_INDEX numeric(1, 0) NOT NULL,
  PARENT_ID numeric(7, 0) NULL,
  CHILDREN_ID varchar(30) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MEMBER_L1_LOG (
  MEMBER_ID numeric(7, 0) NOT NULL,
  GROUP_NO numeric(5, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MEMBER_L2_LOG (
  MEMBER_ID numeric(7, 0) NOT NULL,
  GROUP_NO numeric(5, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MEMBER_L3_LOG (
  MEMBER_ID numeric(7, 0) NOT NULL,
  GROUP_NO numeric(5, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (MEMBER_ID)
)
GO

CREATE TABLE dbo.MANAGER_L1_LOG (
  MANAGER_ID numeric(7, 0) NOT NULL,
  GROUP_NO numeric(5, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (MANAGER_ID)
)
GO

CREATE TABLE dbo.MANAGER_L2_LOG (
  MANAGER_ID numeric(7, 0) NOT NULL,
  GROUP_NO numeric(5, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (MANAGER_ID)
)
GO

CREATE TABLE dbo.MANAGER_L3_LOG (
  MANAGER_ID numeric(7, 0) NOT NULL,
  GROUP_NO numeric(5, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (MANAGER_ID)
)
GO

CREATE TABLE dbo.MANAGER_L4_LOG (
  MANAGER_ID numeric(7, 0) NOT NULL,
  GROUP_NO numeric(5, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (MANAGER_ID)
)
GO

CREATE TABLE dbo.MEMBER_L1_PRE_RPT (
  PARENT_ID numeric(7, 0) NOT NULL,
  SCORE numeric(5, 0) NOT NULL,
  FULL_STATUS numeric(1, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (PARENT_ID)
)
GO

CREATE TABLE dbo.MEMBER_L2_PRE_RPT (
  PARENT_ID numeric(7, 0) NOT NULL,
  SCORE numeric(5, 0) NOT NULL,
  FULL_STATUS numeric(1, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (PARENT_ID)
)
GO

CREATE TABLE dbo.MEMBER_L3_PRE_RPT (
  PARENT_ID numeric(7, 0) NOT NULL,
  SCORE numeric(5, 0) NOT NULL,
  FULL_STATUS numeric(1, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (PARENT_ID)
)
GO

CREATE TABLE dbo.MANAGER_L1_PRE_RPT (
  PARENT_ID numeric(7, 0) NOT NULL,
  SCORE numeric(5, 0) NOT NULL,
  FULL_STATUS numeric(1, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (PARENT_ID)
)
GO

CREATE TABLE dbo.MANAGER_L2_PRE_RPT (
  PARENT_ID numeric(7, 0) NOT NULL,
  SCORE numeric(5, 0) NOT NULL,
  FULL_STATUS numeric(1, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (PARENT_ID)
)
GO

CREATE TABLE dbo.MANAGER_L3_PRE_RPT (
  PARENT_ID numeric(7, 0) NOT NULL,
  SCORE numeric(5, 0) NOT NULL,
  FULL_STATUS numeric(1, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (PARENT_ID)
)
GO

CREATE TABLE dbo.MANAGER_L4_PRE_RPT (
  PARENT_ID numeric(7, 0) NOT NULL,
  SCORE numeric(5, 0) NOT NULL,
  FULL_STATUS numeric(1, 0) NOT NULL,
  PRIMARY KEY CLUSTERED (PARENT_ID)
)
GO