CREATE TABLE dbo.users (
  USER_ID numeric(10, 0) IDENTITY(1, 1) NOT NULL,
  USER_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  PASSWORD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  PRIMARY KEY CLUSTERED (USER_ID)
    WITH (
      PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF,
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
ON [PRIMARY]
GO

CREATE TABLE dbo.USER_ROLE (
  ROLE_ID numeric(10, 0) NOT NULL,
  USER_ID numeric(10, 0) NOT NULL,
  IS_ACTIVE numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (ROLE_ID, USER_ID)
)
GO

CREATE TABLE dbo.ROLES (
  ROLE_ID numeric(10, 0) IDENTITY(1, 1) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  DESCRIPTION varchar(200) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (ROLE_ID),
  UNIQUE (ROLE_CODE)
)
GO

CREATE TABLE dbo.ROLE_OBJECT (
  OBJECT_ID numeric(10, 0) NOT NULL,
  ROLE_ID numeric(10, 0) NOT NULL,
  IS_ACTIVE numeric(1, 0) DEFAULT 1 NOT NULL,
  PRIMARY KEY CLUSTERED (OBJECT_ID, ROLE_ID)
)
GO

CREATE TABLE dbo.OBJECTS (
  OBJECT_ID numeric(10, 0) IDENTITY(1, 1) NOT NULL,
  PARENT_ID numeric(10, 0) NULL,
  OBJECT_CODE varchar(50) NULL,
  DESCRIPTION varchar(200) NULL,
  OBJECT_URL varchar(500) NULL,
  [ORDER] numeric(5, 0) NULL,
  STATUS numeric(1, 0) DEFAULT 1 NULL,
  PRIMARY KEY CLUSTERED (OBJECT_ID),
  UNIQUE (OBJECT_CODE)
)
GO