//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_ws_server.DcapServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountLog", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        private long AccountIDField;
        
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dml {
            get {
                return this.DmlField;
            }
            set {
                if ((object.ReferenceEquals(this.DmlField, value) != true)) {
                    this.DmlField = value;
                    this.RaisePropertyChanged("Dml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DcapServiceReference.DcapServiceSoap")]
    public interface DcapServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        test_ws_server.DcapServiceReference.loginResponse login(test_ws_server.DcapServiceReference.loginRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changePassword", ReplyAction="*")]
        test_ws_server.DcapServiceReference.changePasswordResponse changePassword(test_ws_server.DcapServiceReference.changePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createUser", ReplyAction="*")]
        test_ws_server.DcapServiceReference.createUserResponse createUser(test_ws_server.DcapServiceReference.createUserRequest request);
        
        // CODEGEN: Generating message contract since element name CalculateAccountLogResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateAccountLog", ReplyAction="*")]
        test_ws_server.DcapServiceReference.CalculateAccountLogResponse CalculateAccountLog(test_ws_server.DcapServiceReference.CalculateAccountLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(test_ws_server.DcapServiceReference.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(test_ws_server.DcapServiceReference.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePassword", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.changePasswordRequestBody Body;
        
        public changePasswordRequest() {
        }
        
        public changePasswordRequest(test_ws_server.DcapServiceReference.changePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string confirmPassword;
        
        public changePasswordRequestBody() {
        }
        
        public changePasswordRequestBody(string userName, string oldPassword, string newPassword, string confirmPassword) {
            this.userName = userName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
            this.confirmPassword = confirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.changePasswordResponseBody Body;
        
        public changePasswordResponse() {
        }
        
        public changePasswordResponse(test_ws_server.DcapServiceReference.changePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string changePasswordResult;
        
        public changePasswordResponseBody() {
        }
        
        public changePasswordResponseBody(string changePasswordResult) {
            this.changePasswordResult = changePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUser", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.createUserRequestBody Body;
        
        public createUserRequest() {
        }
        
        public createUserRequest(test_ws_server.DcapServiceReference.createUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string confirmPassword;
        
        public createUserRequestBody() {
        }
        
        public createUserRequestBody(string userName, string password, string confirmPassword) {
            this.userName = userName;
            this.password = password;
            this.confirmPassword = confirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.createUserResponseBody Body;
        
        public createUserResponse() {
        }
        
        public createUserResponse(test_ws_server.DcapServiceReference.createUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createUserResult;
        
        public createUserResponseBody() {
        }
        
        public createUserResponseBody(string createUserResult) {
            this.createUserResult = createUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateAccountLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateAccountLog", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.CalculateAccountLogRequestBody Body;
        
        public CalculateAccountLogRequest() {
        }
        
        public CalculateAccountLogRequest(test_ws_server.DcapServiceReference.CalculateAccountLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CalculateAccountLogRequestBody {
        
        public CalculateAccountLogRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateAccountLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateAccountLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public test_ws_server.DcapServiceReference.CalculateAccountLogResponseBody Body;
        
        public CalculateAccountLogResponse() {
        }
        
        public CalculateAccountLogResponse(test_ws_server.DcapServiceReference.CalculateAccountLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateAccountLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public test_ws_server.DcapServiceReference.AccountLog[] CalculateAccountLogResult;
        
        public CalculateAccountLogResponseBody() {
        }
        
        public CalculateAccountLogResponseBody(test_ws_server.DcapServiceReference.AccountLog[] CalculateAccountLogResult) {
            this.CalculateAccountLogResult = CalculateAccountLogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DcapServiceSoapChannel : test_ws_server.DcapServiceReference.DcapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DcapServiceSoapClient : System.ServiceModel.ClientBase<test_ws_server.DcapServiceReference.DcapServiceSoap>, test_ws_server.DcapServiceReference.DcapServiceSoap {
        
        public DcapServiceSoapClient() {
        }
        
        public DcapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DcapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DcapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DcapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_ws_server.DcapServiceReference.loginResponse test_ws_server.DcapServiceReference.DcapServiceSoap.login(test_ws_server.DcapServiceReference.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string userName, string password) {
            test_ws_server.DcapServiceReference.loginRequest inValue = new test_ws_server.DcapServiceReference.loginRequest();
            inValue.Body = new test_ws_server.DcapServiceReference.loginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            test_ws_server.DcapServiceReference.loginResponse retVal = ((test_ws_server.DcapServiceReference.DcapServiceSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_ws_server.DcapServiceReference.changePasswordResponse test_ws_server.DcapServiceReference.DcapServiceSoap.changePassword(test_ws_server.DcapServiceReference.changePasswordRequest request) {
            return base.Channel.changePassword(request);
        }
        
        public string changePassword(string userName, string oldPassword, string newPassword, string confirmPassword) {
            test_ws_server.DcapServiceReference.changePasswordRequest inValue = new test_ws_server.DcapServiceReference.changePasswordRequest();
            inValue.Body = new test_ws_server.DcapServiceReference.changePasswordRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            inValue.Body.confirmPassword = confirmPassword;
            test_ws_server.DcapServiceReference.changePasswordResponse retVal = ((test_ws_server.DcapServiceReference.DcapServiceSoap)(this)).changePassword(inValue);
            return retVal.Body.changePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_ws_server.DcapServiceReference.createUserResponse test_ws_server.DcapServiceReference.DcapServiceSoap.createUser(test_ws_server.DcapServiceReference.createUserRequest request) {
            return base.Channel.createUser(request);
        }
        
        public string createUser(string userName, string password, string confirmPassword) {
            test_ws_server.DcapServiceReference.createUserRequest inValue = new test_ws_server.DcapServiceReference.createUserRequest();
            inValue.Body = new test_ws_server.DcapServiceReference.createUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.confirmPassword = confirmPassword;
            test_ws_server.DcapServiceReference.createUserResponse retVal = ((test_ws_server.DcapServiceReference.DcapServiceSoap)(this)).createUser(inValue);
            return retVal.Body.createUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_ws_server.DcapServiceReference.CalculateAccountLogResponse test_ws_server.DcapServiceReference.DcapServiceSoap.CalculateAccountLog(test_ws_server.DcapServiceReference.CalculateAccountLogRequest request) {
            return base.Channel.CalculateAccountLog(request);
        }
        
        public test_ws_server.DcapServiceReference.AccountLog[] CalculateAccountLog() {
            test_ws_server.DcapServiceReference.CalculateAccountLogRequest inValue = new test_ws_server.DcapServiceReference.CalculateAccountLogRequest();
            inValue.Body = new test_ws_server.DcapServiceReference.CalculateAccountLogRequestBody();
            test_ws_server.DcapServiceReference.CalculateAccountLogResponse retVal = ((test_ws_server.DcapServiceReference.DcapServiceSoap)(this)).CalculateAccountLog(inValue);
            return retVal.Body.CalculateAccountLogResult;
        }
    }
}
