//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_app.DcapServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long UserIDField;
        
        private long AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoCmndField;
        
        private System.Nullable<System.DateTime> NgayCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoTaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChiNhanhNHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web_app.DcapServiceReference.RoleDto[] AllRolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((this.AccountNumberField.Equals(value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SoCmnd {
            get {
                return this.SoCmndField;
            }
            set {
                if ((object.ReferenceEquals(this.SoCmndField, value) != true)) {
                    this.SoCmndField = value;
                    this.RaisePropertyChanged("SoCmnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> NgayCap {
            get {
                return this.NgayCapField;
            }
            set {
                if ((this.NgayCapField.Equals(value) != true)) {
                    this.NgayCapField = value;
                    this.RaisePropertyChanged("NgayCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SoTaiKhoan {
            get {
                return this.SoTaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.SoTaiKhoanField, value) != true)) {
                    this.SoTaiKhoanField = value;
                    this.RaisePropertyChanged("SoTaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ChiNhanhNH {
            get {
                return this.ChiNhanhNHField;
            }
            set {
                if ((object.ReferenceEquals(this.ChiNhanhNHField, value) != true)) {
                    this.ChiNhanhNHField = value;
                    this.RaisePropertyChanged("ChiNhanhNH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public web_app.DcapServiceReference.RoleDto[] AllRoles {
            get {
                return this.AllRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.AllRolesField, value) != true)) {
                    this.AllRolesField = value;
                    this.RaisePropertyChanged("AllRoles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RoleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RoleCode {
            get {
                return this.RoleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleCodeField, value) != true)) {
                    this.RoleCodeField = value;
                    this.RaisePropertyChanged("RoleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BangKeDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BangKeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long STTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoCmndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NgayCapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoTaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChiNhanhNHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NgayDangKyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NguoiBaoTroField;
        
        private long SoTienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long STT {
            get {
                return this.STTField;
            }
            set {
                if ((this.STTField.Equals(value) != true)) {
                    this.STTField = value;
                    this.RaisePropertyChanged("STT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SoCmnd {
            get {
                return this.SoCmndField;
            }
            set {
                if ((object.ReferenceEquals(this.SoCmndField, value) != true)) {
                    this.SoCmndField = value;
                    this.RaisePropertyChanged("SoCmnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NgayCap {
            get {
                return this.NgayCapField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayCapField, value) != true)) {
                    this.NgayCapField = value;
                    this.RaisePropertyChanged("NgayCap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SoTaiKhoan {
            get {
                return this.SoTaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.SoTaiKhoanField, value) != true)) {
                    this.SoTaiKhoanField = value;
                    this.RaisePropertyChanged("SoTaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ChiNhanhNH {
            get {
                return this.ChiNhanhNHField;
            }
            set {
                if ((object.ReferenceEquals(this.ChiNhanhNHField, value) != true)) {
                    this.ChiNhanhNHField = value;
                    this.RaisePropertyChanged("ChiNhanhNH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string NgayDangKy {
            get {
                return this.NgayDangKyField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayDangKyField, value) != true)) {
                    this.NgayDangKyField = value;
                    this.RaisePropertyChanged("NgayDangKy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string NguoiBaoTro {
            get {
                return this.NguoiBaoTroField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiBaoTroField, value) != true)) {
                    this.NguoiBaoTroField = value;
                    this.RaisePropertyChanged("NguoiBaoTro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public long SoTien {
            get {
                return this.SoTienField;
            }
            set {
                if ((this.SoTienField.Equals(value) != true)) {
                    this.SoTienField = value;
                    this.RaisePropertyChanged("SoTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Thang {
            get {
                return this.ThangField;
            }
            set {
                if ((object.ReferenceEquals(this.ThangField, value) != true)) {
                    this.ThangField = value;
                    this.RaisePropertyChanged("Thang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberNodeDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MemberNodeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AccountIdField;
        
        private long ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DcapServiceReference.DcapServiceSoap")]
    public interface DcapServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        web_app.DcapServiceReference.loginResponse login(web_app.DcapServiceReference.loginRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changePassword", ReplyAction="*")]
        web_app.DcapServiceReference.changePasswordResponse changePassword(web_app.DcapServiceReference.changePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name parentId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        web_app.DcapServiceReference.CreateUserResponse CreateUser(web_app.DcapServiceReference.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        web_app.DcapServiceReference.UpdateUserResponse UpdateUser(web_app.DcapServiceReference.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserAdmin", ReplyAction="*")]
        web_app.DcapServiceReference.CreateUserAdminResponse CreateUserAdmin(web_app.DcapServiceReference.CreateUserAdminRequest request);
        
        // CODEGEN: Generating message contract since element name parentId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUser", ReplyAction="*")]
        web_app.DcapServiceReference.SearchUserResponse SearchUser(web_app.DcapServiceReference.SearchUserRequest request);
        
        // CODEGEN: Generating message contract since element name SearchBangKeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchBangKe", ReplyAction="*")]
        web_app.DcapServiceReference.SearchBangKeResponse SearchBangKe(web_app.DcapServiceReference.SearchBangKeRequest request);
        
        // CODEGEN: Generating message contract since element name soCmnd from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUserInfo", ReplyAction="*")]
        web_app.DcapServiceReference.SearchUserInfoResponse SearchUserInfo(web_app.DcapServiceReference.SearchUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name idMember from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchMemberNodeDto", ReplyAction="*")]
        web_app.DcapServiceReference.SearchMemberNodeDtoResponse SearchMemberNodeDto(web_app.DcapServiceReference.SearchMemberNodeDtoRequest request);
        
        // CODEGEN: Generating message contract since element name accountNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParentNodeByChildNo", ReplyAction="*")]
        web_app.DcapServiceReference.GetParentNodeByChildNoResponse GetParentNodeByChildNo(web_app.DcapServiceReference.GetParentNodeByChildNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateAccountLog", ReplyAction="*")]
        int CalculateAccountLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBonusOfAccountTree", ReplyAction="*")]
        int CalculateBonusOfAccountTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteApprovedManager", ReplyAction="*")]
        int ExecuteApprovedManager();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateBonusOfManagerTree", ReplyAction="*")]
        int CalculateBonusOfManagerTree();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(web_app.DcapServiceReference.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(web_app.DcapServiceReference.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web_app.DcapServiceReference.UserDto loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(web_app.DcapServiceReference.UserDto loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePassword", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.changePasswordRequestBody Body;
        
        public changePasswordRequest() {
        }
        
        public changePasswordRequest(web_app.DcapServiceReference.changePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string confirmPassword;
        
        public changePasswordRequestBody() {
        }
        
        public changePasswordRequestBody(string userName, string oldPassword, string newPassword, string confirmPassword) {
            this.userName = userName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
            this.confirmPassword = confirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.changePasswordResponseBody Body;
        
        public changePasswordResponse() {
        }
        
        public changePasswordResponse(web_app.DcapServiceReference.changePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string changePasswordResult;
        
        public changePasswordResponseBody() {
        }
        
        public changePasswordResponseBody(string changePasswordResult) {
            this.changePasswordResult = changePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(web_app.DcapServiceReference.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string directParentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ngaySinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string soCmnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ngayCap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string soDienThoai;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string diaChi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string gioiTinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string soTaiKhoan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string chiNhanhNH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string photoUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string createdBy;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string parentId, string directParentId, string userName, string ngaySinh, string soCmnd, string ngayCap, string soDienThoai, string diaChi, string gioiTinh, string soTaiKhoan, string chiNhanhNH, string photoUrl, string createdBy) {
            this.parentId = parentId;
            this.directParentId = directParentId;
            this.userName = userName;
            this.ngaySinh = ngaySinh;
            this.soCmnd = soCmnd;
            this.ngayCap = ngayCap;
            this.soDienThoai = soDienThoai;
            this.diaChi = diaChi;
            this.gioiTinh = gioiTinh;
            this.soTaiKhoan = soTaiKhoan;
            this.chiNhanhNH = chiNhanhNH;
            this.photoUrl = photoUrl;
            this.createdBy = createdBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(web_app.DcapServiceReference.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(string CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(web_app.DcapServiceReference.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ngaySinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string soCmnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ngayCap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string soDienThoai;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string diaChi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string gioiTinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string soTaiKhoan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string chiNhanhNH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string photoUrl;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(string userName, string fullName, string ngaySinh, string soCmnd, string ngayCap, string soDienThoai, string diaChi, string gioiTinh, string soTaiKhoan, string chiNhanhNH, string photoUrl) {
            this.userName = userName;
            this.fullName = fullName;
            this.ngaySinh = ngaySinh;
            this.soCmnd = soCmnd;
            this.ngayCap = ngayCap;
            this.soDienThoai = soDienThoai;
            this.diaChi = diaChi;
            this.gioiTinh = gioiTinh;
            this.soTaiKhoan = soTaiKhoan;
            this.chiNhanhNH = chiNhanhNH;
            this.photoUrl = photoUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(web_app.DcapServiceReference.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(string UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserAdmin", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.CreateUserAdminRequestBody Body;
        
        public CreateUserAdminRequest() {
        }
        
        public CreateUserAdminRequest(web_app.DcapServiceReference.CreateUserAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string createdBy;
        
        public CreateUserAdminRequestBody() {
        }
        
        public CreateUserAdminRequestBody(string userName, string fullName, string roleCode, string createdBy) {
            this.userName = userName;
            this.fullName = fullName;
            this.roleCode = roleCode;
            this.createdBy = createdBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.CreateUserAdminResponseBody Body;
        
        public CreateUserAdminResponse() {
        }
        
        public CreateUserAdminResponse(web_app.DcapServiceReference.CreateUserAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserAdminResult;
        
        public CreateUserAdminResponseBody() {
        }
        
        public CreateUserAdminResponseBody(string CreateUserAdminResult) {
            this.CreateUserAdminResult = CreateUserAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUser", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchUserRequestBody Body;
        
        public SearchUserRequest() {
        }
        
        public SearchUserRequest(web_app.DcapServiceReference.SearchUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string directParentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ngaySinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string soCmnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ngayCap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string soDienThoai;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string diaChi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string gioiTinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string soTaiKhoan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string chiNhanhNH;
        
        public SearchUserRequestBody() {
        }
        
        public SearchUserRequestBody(string parentId, string directParentId, string userName, string ngaySinh, string soCmnd, string ngayCap, string soDienThoai, string diaChi, string gioiTinh, string soTaiKhoan, string chiNhanhNH) {
            this.parentId = parentId;
            this.directParentId = directParentId;
            this.userName = userName;
            this.ngaySinh = ngaySinh;
            this.soCmnd = soCmnd;
            this.ngayCap = ngayCap;
            this.soDienThoai = soDienThoai;
            this.diaChi = diaChi;
            this.gioiTinh = gioiTinh;
            this.soTaiKhoan = soTaiKhoan;
            this.chiNhanhNH = chiNhanhNH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchUserResponseBody Body;
        
        public SearchUserResponse() {
        }
        
        public SearchUserResponse(web_app.DcapServiceReference.SearchUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchUserResult;
        
        public SearchUserResponseBody() {
        }
        
        public SearchUserResponseBody(string SearchUserResult) {
            this.SearchUserResult = SearchUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchBangKeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchBangKe", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchBangKeRequestBody Body;
        
        public SearchBangKeRequest() {
        }
        
        public SearchBangKeRequest(web_app.DcapServiceReference.SearchBangKeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchBangKeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<System.DateTime> thangKeKhai;
        
        public SearchBangKeRequestBody() {
        }
        
        public SearchBangKeRequestBody(System.Nullable<System.DateTime> thangKeKhai) {
            this.thangKeKhai = thangKeKhai;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchBangKeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchBangKeResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchBangKeResponseBody Body;
        
        public SearchBangKeResponse() {
        }
        
        public SearchBangKeResponse(web_app.DcapServiceReference.SearchBangKeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchBangKeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web_app.DcapServiceReference.BangKeDto[] SearchBangKeResult;
        
        public SearchBangKeResponseBody() {
        }
        
        public SearchBangKeResponseBody(web_app.DcapServiceReference.BangKeDto[] SearchBangKeResult) {
            this.SearchBangKeResult = SearchBangKeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchUserInfoRequestBody Body;
        
        public SearchUserInfoRequest() {
        }
        
        public SearchUserInfoRequest(web_app.DcapServiceReference.SearchUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string soCmnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idThanhVien;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hoTen;
        
        public SearchUserInfoRequestBody() {
        }
        
        public SearchUserInfoRequestBody(string soCmnd, string idThanhVien, string hoTen) {
            this.soCmnd = soCmnd;
            this.idThanhVien = idThanhVien;
            this.hoTen = hoTen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchUserInfoResponseBody Body;
        
        public SearchUserInfoResponse() {
        }
        
        public SearchUserInfoResponse(web_app.DcapServiceReference.SearchUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web_app.DcapServiceReference.UserDto[] SearchUserInfoResult;
        
        public SearchUserInfoResponseBody() {
        }
        
        public SearchUserInfoResponseBody(web_app.DcapServiceReference.UserDto[] SearchUserInfoResult) {
            this.SearchUserInfoResult = SearchUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchMemberNodeDtoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchMemberNodeDto", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchMemberNodeDtoRequestBody Body;
        
        public SearchMemberNodeDtoRequest() {
        }
        
        public SearchMemberNodeDtoRequest(web_app.DcapServiceReference.SearchMemberNodeDtoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchMemberNodeDtoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idMember;
        
        public SearchMemberNodeDtoRequestBody() {
        }
        
        public SearchMemberNodeDtoRequestBody(string idMember) {
            this.idMember = idMember;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchMemberNodeDtoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchMemberNodeDtoResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.SearchMemberNodeDtoResponseBody Body;
        
        public SearchMemberNodeDtoResponse() {
        }
        
        public SearchMemberNodeDtoResponse(web_app.DcapServiceReference.SearchMemberNodeDtoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchMemberNodeDtoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web_app.DcapServiceReference.MemberNodeDto[] SearchMemberNodeDtoResult;
        
        public SearchMemberNodeDtoResponseBody() {
        }
        
        public SearchMemberNodeDtoResponseBody(web_app.DcapServiceReference.MemberNodeDto[] SearchMemberNodeDtoResult) {
            this.SearchMemberNodeDtoResult = SearchMemberNodeDtoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParentNodeByChildNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParentNodeByChildNo", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.GetParentNodeByChildNoRequestBody Body;
        
        public GetParentNodeByChildNoRequest() {
        }
        
        public GetParentNodeByChildNoRequest(web_app.DcapServiceReference.GetParentNodeByChildNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParentNodeByChildNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountNumber;
        
        public GetParentNodeByChildNoRequestBody() {
        }
        
        public GetParentNodeByChildNoRequestBody(string accountNumber) {
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParentNodeByChildNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParentNodeByChildNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public web_app.DcapServiceReference.GetParentNodeByChildNoResponseBody Body;
        
        public GetParentNodeByChildNoResponse() {
        }
        
        public GetParentNodeByChildNoResponse(web_app.DcapServiceReference.GetParentNodeByChildNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParentNodeByChildNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web_app.DcapServiceReference.MemberNodeDto GetParentNodeByChildNoResult;
        
        public GetParentNodeByChildNoResponseBody() {
        }
        
        public GetParentNodeByChildNoResponseBody(web_app.DcapServiceReference.MemberNodeDto GetParentNodeByChildNoResult) {
            this.GetParentNodeByChildNoResult = GetParentNodeByChildNoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DcapServiceSoapChannel : web_app.DcapServiceReference.DcapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DcapServiceSoapClient : System.ServiceModel.ClientBase<web_app.DcapServiceReference.DcapServiceSoap>, web_app.DcapServiceReference.DcapServiceSoap {
        
        public DcapServiceSoapClient() {
        }
        
        public DcapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DcapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DcapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DcapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.loginResponse web_app.DcapServiceReference.DcapServiceSoap.login(web_app.DcapServiceReference.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public web_app.DcapServiceReference.UserDto login(string userName, string password) {
            web_app.DcapServiceReference.loginRequest inValue = new web_app.DcapServiceReference.loginRequest();
            inValue.Body = new web_app.DcapServiceReference.loginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            web_app.DcapServiceReference.loginResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.changePasswordResponse web_app.DcapServiceReference.DcapServiceSoap.changePassword(web_app.DcapServiceReference.changePasswordRequest request) {
            return base.Channel.changePassword(request);
        }
        
        public string changePassword(string userName, string oldPassword, string newPassword, string confirmPassword) {
            web_app.DcapServiceReference.changePasswordRequest inValue = new web_app.DcapServiceReference.changePasswordRequest();
            inValue.Body = new web_app.DcapServiceReference.changePasswordRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            inValue.Body.confirmPassword = confirmPassword;
            web_app.DcapServiceReference.changePasswordResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).changePassword(inValue);
            return retVal.Body.changePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.CreateUserResponse web_app.DcapServiceReference.DcapServiceSoap.CreateUser(web_app.DcapServiceReference.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public string CreateUser(string parentId, string directParentId, string userName, string ngaySinh, string soCmnd, string ngayCap, string soDienThoai, string diaChi, string gioiTinh, string soTaiKhoan, string chiNhanhNH, string photoUrl, string createdBy) {
            web_app.DcapServiceReference.CreateUserRequest inValue = new web_app.DcapServiceReference.CreateUserRequest();
            inValue.Body = new web_app.DcapServiceReference.CreateUserRequestBody();
            inValue.Body.parentId = parentId;
            inValue.Body.directParentId = directParentId;
            inValue.Body.userName = userName;
            inValue.Body.ngaySinh = ngaySinh;
            inValue.Body.soCmnd = soCmnd;
            inValue.Body.ngayCap = ngayCap;
            inValue.Body.soDienThoai = soDienThoai;
            inValue.Body.diaChi = diaChi;
            inValue.Body.gioiTinh = gioiTinh;
            inValue.Body.soTaiKhoan = soTaiKhoan;
            inValue.Body.chiNhanhNH = chiNhanhNH;
            inValue.Body.photoUrl = photoUrl;
            inValue.Body.createdBy = createdBy;
            web_app.DcapServiceReference.CreateUserResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.UpdateUserResponse web_app.DcapServiceReference.DcapServiceSoap.UpdateUser(web_app.DcapServiceReference.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public string UpdateUser(string userName, string fullName, string ngaySinh, string soCmnd, string ngayCap, string soDienThoai, string diaChi, string gioiTinh, string soTaiKhoan, string chiNhanhNH, string photoUrl) {
            web_app.DcapServiceReference.UpdateUserRequest inValue = new web_app.DcapServiceReference.UpdateUserRequest();
            inValue.Body = new web_app.DcapServiceReference.UpdateUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.fullName = fullName;
            inValue.Body.ngaySinh = ngaySinh;
            inValue.Body.soCmnd = soCmnd;
            inValue.Body.ngayCap = ngayCap;
            inValue.Body.soDienThoai = soDienThoai;
            inValue.Body.diaChi = diaChi;
            inValue.Body.gioiTinh = gioiTinh;
            inValue.Body.soTaiKhoan = soTaiKhoan;
            inValue.Body.chiNhanhNH = chiNhanhNH;
            inValue.Body.photoUrl = photoUrl;
            web_app.DcapServiceReference.UpdateUserResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.CreateUserAdminResponse web_app.DcapServiceReference.DcapServiceSoap.CreateUserAdmin(web_app.DcapServiceReference.CreateUserAdminRequest request) {
            return base.Channel.CreateUserAdmin(request);
        }
        
        public string CreateUserAdmin(string userName, string fullName, string roleCode, string createdBy) {
            web_app.DcapServiceReference.CreateUserAdminRequest inValue = new web_app.DcapServiceReference.CreateUserAdminRequest();
            inValue.Body = new web_app.DcapServiceReference.CreateUserAdminRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.fullName = fullName;
            inValue.Body.roleCode = roleCode;
            inValue.Body.createdBy = createdBy;
            web_app.DcapServiceReference.CreateUserAdminResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).CreateUserAdmin(inValue);
            return retVal.Body.CreateUserAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.SearchUserResponse web_app.DcapServiceReference.DcapServiceSoap.SearchUser(web_app.DcapServiceReference.SearchUserRequest request) {
            return base.Channel.SearchUser(request);
        }
        
        public string SearchUser(string parentId, string directParentId, string userName, string ngaySinh, string soCmnd, string ngayCap, string soDienThoai, string diaChi, string gioiTinh, string soTaiKhoan, string chiNhanhNH) {
            web_app.DcapServiceReference.SearchUserRequest inValue = new web_app.DcapServiceReference.SearchUserRequest();
            inValue.Body = new web_app.DcapServiceReference.SearchUserRequestBody();
            inValue.Body.parentId = parentId;
            inValue.Body.directParentId = directParentId;
            inValue.Body.userName = userName;
            inValue.Body.ngaySinh = ngaySinh;
            inValue.Body.soCmnd = soCmnd;
            inValue.Body.ngayCap = ngayCap;
            inValue.Body.soDienThoai = soDienThoai;
            inValue.Body.diaChi = diaChi;
            inValue.Body.gioiTinh = gioiTinh;
            inValue.Body.soTaiKhoan = soTaiKhoan;
            inValue.Body.chiNhanhNH = chiNhanhNH;
            web_app.DcapServiceReference.SearchUserResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).SearchUser(inValue);
            return retVal.Body.SearchUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.SearchBangKeResponse web_app.DcapServiceReference.DcapServiceSoap.SearchBangKe(web_app.DcapServiceReference.SearchBangKeRequest request) {
            return base.Channel.SearchBangKe(request);
        }
        
        public web_app.DcapServiceReference.BangKeDto[] SearchBangKe(System.Nullable<System.DateTime> thangKeKhai) {
            web_app.DcapServiceReference.SearchBangKeRequest inValue = new web_app.DcapServiceReference.SearchBangKeRequest();
            inValue.Body = new web_app.DcapServiceReference.SearchBangKeRequestBody();
            inValue.Body.thangKeKhai = thangKeKhai;
            web_app.DcapServiceReference.SearchBangKeResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).SearchBangKe(inValue);
            return retVal.Body.SearchBangKeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.SearchUserInfoResponse web_app.DcapServiceReference.DcapServiceSoap.SearchUserInfo(web_app.DcapServiceReference.SearchUserInfoRequest request) {
            return base.Channel.SearchUserInfo(request);
        }
        
        public web_app.DcapServiceReference.UserDto[] SearchUserInfo(string soCmnd, string idThanhVien, string hoTen) {
            web_app.DcapServiceReference.SearchUserInfoRequest inValue = new web_app.DcapServiceReference.SearchUserInfoRequest();
            inValue.Body = new web_app.DcapServiceReference.SearchUserInfoRequestBody();
            inValue.Body.soCmnd = soCmnd;
            inValue.Body.idThanhVien = idThanhVien;
            inValue.Body.hoTen = hoTen;
            web_app.DcapServiceReference.SearchUserInfoResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).SearchUserInfo(inValue);
            return retVal.Body.SearchUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.SearchMemberNodeDtoResponse web_app.DcapServiceReference.DcapServiceSoap.SearchMemberNodeDto(web_app.DcapServiceReference.SearchMemberNodeDtoRequest request) {
            return base.Channel.SearchMemberNodeDto(request);
        }
        
        public web_app.DcapServiceReference.MemberNodeDto[] SearchMemberNodeDto(string idMember) {
            web_app.DcapServiceReference.SearchMemberNodeDtoRequest inValue = new web_app.DcapServiceReference.SearchMemberNodeDtoRequest();
            inValue.Body = new web_app.DcapServiceReference.SearchMemberNodeDtoRequestBody();
            inValue.Body.idMember = idMember;
            web_app.DcapServiceReference.SearchMemberNodeDtoResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).SearchMemberNodeDto(inValue);
            return retVal.Body.SearchMemberNodeDtoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web_app.DcapServiceReference.GetParentNodeByChildNoResponse web_app.DcapServiceReference.DcapServiceSoap.GetParentNodeByChildNo(web_app.DcapServiceReference.GetParentNodeByChildNoRequest request) {
            return base.Channel.GetParentNodeByChildNo(request);
        }
        
        public web_app.DcapServiceReference.MemberNodeDto GetParentNodeByChildNo(string accountNumber) {
            web_app.DcapServiceReference.GetParentNodeByChildNoRequest inValue = new web_app.DcapServiceReference.GetParentNodeByChildNoRequest();
            inValue.Body = new web_app.DcapServiceReference.GetParentNodeByChildNoRequestBody();
            inValue.Body.accountNumber = accountNumber;
            web_app.DcapServiceReference.GetParentNodeByChildNoResponse retVal = ((web_app.DcapServiceReference.DcapServiceSoap)(this)).GetParentNodeByChildNo(inValue);
            return retVal.Body.GetParentNodeByChildNoResult;
        }
        
        public int CalculateAccountLog() {
            return base.Channel.CalculateAccountLog();
        }
        
        public int CalculateBonusOfAccountTree() {
            return base.Channel.CalculateBonusOfAccountTree();
        }
        
        public int ExecuteApprovedManager() {
            return base.Channel.ExecuteApprovedManager();
        }
        
        public int CalculateBonusOfManagerTree() {
            return base.Channel.CalculateBonusOfManagerTree();
        }
    }
}
